api_version = "2025-07"
uid = "2377e7ee-c8b8-1b27-59bd-e4fbf0f369103cd288cf"

[[extensions]]
type = "ui_extension"
name = "ReviewReward Thank You Widget"
handle = "review-reward-thank-you"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"
